language: go
go:
- 1.4.3
- 1.5.3
- tip
sudo: false
install:
- go get -v ./...
- export PATH=$PATH:$HOME/gopath/bin
- curl https://bitbucket.org/birkenfeld/pygments-main/get/2.1.tar.gz -L -o 2.1.tar.gz
- mkdir -p ${HOME}/bin
- tar -xf 2.1.tar.gz
- mv birkenfeld-pygments-main-34530db252d3/* ${HOME}/bin
- rm -rf birkenfeld-pygments-main-34530db252d3
script:
- export PATH=${PATH}:${HOME}/bin
- make
- make docs
notifications:
  slack:
    secure: bMYXaoSEGoNdqR0t1VnMAv/4V9PSOhEWyekdJM7p9WmKjJi2yKy0k77uRmwf+5Mrz5GLs3CkZnDha/8cSFld3KEN9SC6QYmIBF/1Pd/5mKHFQOI81i7sTlhrdMv897+6sofEtbBNq1jffhVGVttbMrMWwCTNZu0NrCGBVsDmb44=
deploy:
  provider: gcs
  access_key_id: GOOGDIIIVPY7O6DG3PSZ
  secret_access_key:
    secure: wweE3suXU9B8UWGYUSrqUlxNoH+pLp+sd1ayGMtsjOzTN+U1BveRIwavkJCOUVq1A2hHhe7oC/24XdS+MdxylQcnDTyHwRFBcf/Q+TTfLM4EPmOErQkw15Zy/MP/8velLGrNZk6Je1XiJnNLRbFVcCJRIC384Ka1LVe4e3yooMPt5vVNtJEYdiv08ANNGD3ge/Am5JdQ3ZjRr4ARTIyLUYi2RNeDn0Faj2M4i60/Jo9mcm9pyZHA1sZxnUNxwYNb12qwi02rl60ZCbBhI22yeUhzeNC2cBPOjTwaI0+w+rY1D0bv7/JeQyk0eMK5MZm6cVmQl3tFpyesr9ayWdpTz36EbzbgW81wedHfDlYBbq5HkAd4uxaF6hUknYKcq83arOhXrlqvpxs6/IN/RqlIyjjKvfwM+1Pl+E2j+mXX+RYNwLSR4YCiqFWwwRkRCOIEuopCqs/2ZaZSoqpILRvE/vBSPC4k4p4xUam3ne+1EkugwLMr6nxo8jVw4l0UmQaQtYhy9jge0J9nGe/X2OUXhio4wAAk5+Vh979j6KBTwjdCf2IJrYNHN3nWZnFH3EM424junHcJXFhTsC+KHVIEXUcR1nkeJNfFp275SJVPGcGhEjTVcCsQ/NDTwfY0Xr4INbkJR81/w36Edk8xOfGiXZtuWwJJJk4/8dL+zHAXWVI=
  bucket: goa.design
  local-dir: public/reference
  upload-dir: reference
  skip-cleanup: true
  acl: public-read
  cache-control: no-cache
  on:
    repo: goadesign/gorma
    go: '1.5.3'
